=== afomin-basejava/masterjava/src/main/resources/payload.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://javaops.ru"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://javaops.ru"
           elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:element name="Payload">
        <xs:complexType>
            <xs:all>
                <!--    1.1 добавить проекты. Имеют название (например topjava, masterjava) и описание-->
                <xs:element name="Projects">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="unbounded">
                            <xs:element ref="Project"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Cities">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="unbounded">
                            <xs:element ref="City"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Users">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="User"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="User">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="fullName"/>
            </xs:sequence>
            <xs:attribute type="flagType" name="flag" use="required"/>
            <xs:attribute type="xs:IDREF" name="city" use="required"/>
            <!--1.3 сделать User.email аттрибутом.-->
            <!--https://github.com/metashare/META-SHARE/issues/527-->
            <xs:attribute type="emailAddress" name="email"/>
            <!--1.4 реализовать принадлежность участников разным группам (Admin состоит в группах topjava07, topjava08, masterjava01)-->
            <xs:attribute type="xs:IDREFS" name="userGroup"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="flagType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="active"/>
            <xs:enumeration value="deleted"/>
            <xs:enumeration value="superuser"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="City" type="cityType"/>

    <xs:complexType name="cityType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="id" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!--1.1 добавить проекты. Имеют название (например topjava, masterjava) и описание-->
    <xs:element name="Project">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="description"/>
                <xs:sequence minOccurs="1" maxOccurs="5">
                    <!--1.2 добавить группы. Они имеют название и тип (REGISTERING/CURRENT/FINISHED) и принадлежат проекту.-->
                    <xs:element name="Group">
                        <xs:complexType>
                            <!--1.4 реализовать принадлежность участников разным группам (Admin состоит в группах topjava07, topjava08, masterjava01)-->
                            <xs:attribute type="xs:ID" name="name" use="required"/>
                            <xs:attribute type="groupType" name="type" use="required"/>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="groupType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="REGISTERING"/>
            <xs:enumeration value="CURRENT"/>
            <xs:enumeration value="FINISHED"/>
        </xs:restriction>
    </xs:simpleType>

    <!--https://github.com/metashare/META-SHARE/issues/527-->
    <xs:simpleType name="emailAddress">
        <xs:restriction base="xs:token">
            <xs:maxLength value="254"/>
            <xs:pattern value="[_\-a-zA-Z0-9\.\+]+@[a-zA-Z0-9](\.?[\-a-zA-Z0-9]*[a-zA-Z0-9])*"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== afomin-basejava/masterjava/src/main/resources/payload.xml
<Payload xmlns="http://javaops.ru"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://javaops.ru payload.xsd">
<!--    1.1 добавить проекты. Имеют название (например topjava, masterjava) и описание-->
    <Projects>
        <Project name="topjava">
            <description>Enterprise Java-разработчик (TopJava)</description>
<!--            1.2 добавить группы. Они имеют название и тип (REGISTERING/CURRENT/FINISHED) и принадлежат проекту.-->
            <Group name="topjava01" type="FINISHED"/>
            <Group name="topjava02" type="CURRENT"/>
            <Group name="topjava03" type="REGISTERING"/>
        </Project>
        <Project name="masterjava">
            <description>Многомодульный Maven, многопоточность, JavaEE</description>
            <Group name="masterjava01" type="CURRENT"/>
        </Project>
    </Projects>
    <Users>
<!--        1.3 сделать User.email аттрибутом.-->
<!--        1.4 реализовать принадлежность участников разным группам (Admin состоит в группах topjava07, topjava08, masterjava01)-->
        <User flag="active" city="kiv" email="active@ru.ru" userGroup="topjava01">
            <fullName>full Name</fullName>
        </User>
        <User flag="active" city="kiv" email="active1@r" userGroup="topjava03">
            <fullName>another User</fullName>
        </User>
        <User flag="superuser" city="spb" email="superuser@r.r" userGroup="topjava02 topjava03 masterjava01">
            <fullName>Axmin</fullName>
        </User>
        <User flag="deleted" city="spb" email="deleted@y.y">
            <fullName>Deleted</fullName>
        </User>
    </Users>
    <Cities>
        <City id="spb">Санкт-Петербург</City>
        <City id="kiv">Киев</City>
        <City id="mnsk">Минск</City>
    </Cities>
</Payload>
